### ISSUE TITLE
Create file from shortcut (Alt+N) doesn't create file from current opened file's containing folder

### ISSUE THREAD

**Issue by kenvunz** [math2001/FileManager#16]
**Platform:**
macOS

**Action:**
Create new file via shortcut (Alt+N) while there is a file open in the view

**Expected behaviour:**
New file should be created from the opened file's container folder

**Actual behaviour:**
New file is default to create from project root

---

I have a bit of a dive into the code, and if I commented out this block of code in [`FMcommands/create.py`](https://github.com/math2001/FileManager/blob/master/FMcommands/create.py#L58-L61):

```python
...
elif self.folders:
     # it is going to be interactive, so it'll be
     # understood from the input itself
    create_from = None
...
```
then creating new file feature works as expected.

**Comment by math2001** [comment]
It isn't an expected behavior, but it's definitely a good idea. Maybe you haven't read the docs? In this case, you're very likely to be missing on some stuff that'll save you time. In this case, you can use the alias `$here` (which is just an alias for the alias `$file_path`). So, just `$here/` and then your file name will do the trick.

Typing `$here/` all the time's gonna annoy you, I know. What you can do is add an other shortcut (or overwrite the original one) so that the initial text is `$here/`. In my case, here's what I've done:

```json
{
    "keys": ["ctrl+n"],
    "command": "fm_create",
    "args": {
        "initial_text": "$here/"
    }    
}
```

Just to let you know, the expected behavior is that the "base" is the first folder (you can see it by showing the side bar). If there is none, *then* it picks the currently focused file.

So, I *really* recommend you have a look at the [docs](https://math2001.github.io/FileManager/). In this case, you want to look [here](https://math2001.github.io/FileManager/references/aliases/).

What I can also do is add a setting so that is *always* uses the currently focused file, whether there is a folder in the current window or not. Would you like to have that? or the current solution works fine for you?

**Comment by kenvunz** [comment]
@math2001 I did read your (super awesome) docs, but I guess I missed out the important bits about the order of file creation location 😅 

anyway, your sugesstion about setting `inittial_text` works like a charm! So I don't think we need to complicate your plugin further with a setting to always uses the current focused file

Cheers,
Ken

**Comment by math2001** [comment]
No worries! 😉

> I did read your (super awesome) docs

What do you find "super awesome" about it? The theme? In this case, I agree. It's Material on mkdocs.

**Comment by kenvunz** [comment]
@math2001 yes the theme and the amount of details you've put into, haven't seen anything like that for a Sublime Text plugin before :)

**Comment by math2001** [comment]
> haven't seen anything like that for a Sublime Text plugin before :)

Thank you! Maybe you haven't used any packages of @facelessuser then...  He's the one that told me to use mkdocs. And he changed his theme to Material too (he use to use the readthedocs one). These docs are full of details too

**Comment by facelessuser** [comment]
I'm glad to see some other plugins are picking up using MkDocs 🙂 .
