### ISSUE TITLE
macOS: Rename "Open in Explorer" to "Open in Finder"

### ISSUE THREAD

**Issue by franciscolourenco** [math2001/FileManager#18]
When system is macOS, rename the command `Open in Explorer` to `Open in Finder`.

**Comment by jpcirrus** [comment]
This change was not also applied to `FileManager.sublime-commands`.

**Comment by math2001** [comment]
Oh yeah I didn't realise that. I don't think the `platform` field is supported in `.sublime-commands` though, so that means that we'd have to create a "wrapper" command that would only be shown on Mac, and call the actual find in explorer (and the original find in explorer would be enabled but not visible). It's hacky, but I think it'd work... Would you wanna try to implement that @jpcirrus?

**Comment by jpcirrus** [comment]
Yes, had tried to add a `platform` key to `FileManager.sublime-commands` and both commands appeared in the panel ☹️ . Unfortunately, I haven't worked in Python since 2013, and only in the last month am coming back to ST after having moved away in 2014 due to "the disappearance" and having been previously burnt with TextMate, so it would take me some time and I have some assignments to submit in the next couple of weeks, so I'm probably not the person for it now.

But, on OSX, to open a path in the Finder you can use the command `open -R path`. `R` for reveal.

**Comment by math2001** [comment]
Just a quick note: FileManager uses the Sublime Text command `open_dir` to remain consistent with the rest of the ST. However, I'm not sure if does the "reveal" behavior you wanted with `open -R path`. I'm assuming it does (I think it did it on Windows, and ST tends to get these kind of things right). I'd just like to confirm with you @jpcirrus, because it should be an easy fix otherwise for FileManager.

Extra in case: I've implemented this behavior a bit differently than described in the comment above, see the commit message for details.

**Comment by jpcirrus** [comment]
Yes, it works great on macOS. Thanks!
