### ISSUE TITLE
Auto close empty file not work?

### ISSUE THREAD

**Issue by LynnHo** [math2001/FileManager#27]
@math2001 I set auto_close_empty_groups=true, but it doesn't work like SideBarEnhancements (I try on ubuntu with subl3). Besides, is there any possibility to add cut/paste to the menu?

**Comment by math2001** [comment]
> Besides, is there any possibility to add cut/paste to the menu?

That's not planned. FileManager just tries to be lightweight, and I feel that if you are going to such big fancy file moves, then you should use an actual file manager, not the text editor's.

Indeed, `auto_close_empty_group` doesn't work for me either. I'll look into that later on

**Comment by math2001** [comment]
Omg that was a very stupid and simple bug. I was checking the view's settings, instead of FileManager's settings. Just a one liner. I'll push the fix :slightly_smiling_face:

**Comment by math2001** [comment]
Actually, I just realised that it doesn't really make sense for this feature to be in FileManager. I think it should be in it's own package (something like `AutoCloseEmptyGroup` maybe?)

It would be a tiny package, sure, but this feature doesn't interact in any way with the rest of FileManager, and I don't think a user would expect it either (ie. think about a user uninstalling FileManager, and suddenly seeing that their empty groups don't close automatically. They certainly could want that feature without FileManager). Considering that the default value for this setting was `false`, this might even be the opportunity to split now.

What do you think @LynnHo ?

**Comment by LynnHo** [comment]
@math2001 Thanks for fixing the bug! I totally agree that it should be an independent package. And actually, I wrote an `AutoCloseEmptyGroup` for myself. The code is below, (I am not very familiar with sublime coding, but it works)

```
class AutoCloseEmptyGroupCommand(sublime_plugin.EventListener):
    """AutoCloseEmptyGroup.

    Settings
    --------
    view_control_close_auto_close_empty_group: boolean

    """

    def on_hover(self, view, point, hover_zone):
        auto_close_empty_group = self.settings.get('view_control_close_auto_close_empty_group', False)

        if auto_close_empty_group:
            window = sublime.active_window()

            n_group = window.num_groups()
            non_empty_group_id = []
            for i in range(n_group):
                if window.sheets_in_group(i):
                    non_empty_group_id.append(i)

            if len(non_empty_group_id) == 1 and len(non_empty_group_id) < n_group:
                for s in window.sheets_in_group(non_empty_group_id[0]):
                    window.set_sheet_index(s, 0, len(window.sheets_in_group(0)))
                    window.focus_group(0)  # to avoid crash
                window.run_command('set_layout', {"cols": [0.0, 1.0], "rows": [0.0, 1.0], "cells": [[0, 0, 1, 1]]})
```

**Comment by math2001** [comment]
Alright sweet, I'll make an other package and submit it to package control :slightly_smiling_face: 

I don't think `on_hover` is the most appropriate event to listen for. FileManager uses `on_close` (with a little `on_pre_close` because ST is a bit quirky sometimes), so that we do as little error checking as possible. That also comes at the cost of not being able to close the pane automatically if you drag the tab out of a group with the mouse. But if you want to do that, then you should probably use `View -> Groups -> Close Group` (which you probably want to add to the command palette too).

Also, it uses `window.run_command('close_pane')` instead of forcefully using the single layout (so if for some odd reason you have nested groups ie. 3 columns for example, it wouldn't destroy everything).

I'll close once I will have split up FileManager and AutoCloseEmptyGroup.

**Comment by math2001** [comment]
Alright, now we just have to wait for [the PR to be merged](https://github.com/wbond/package_control_channel/pull/7800) (i'll remove the feature from FileManager as soon as that happens)

**Comment by math2001** [comment]
It's been merged! :tada: Thank you for you help @LynnHo :hearts:

**Comment by LynnHo** [comment]
@math2001 Well done!
