### ISSUE TITLE
Setting for not opening files on rename

### ISSUE THREAD

**Issue by dhelonious** [math2001/FileManager#29]
When a file is renamed, it it automatically opened. In most cases I don't want to see or edit the contents of the file at that moment. However, to allow for that behavior I would suggest to add a setting to prevent it.

**Comment by math2001** [comment]
Oh wait I just realised what you're doing: you are renaming from the side bar, right? Maybe we are able to automatically detect that...

**Comment by math2001** [comment]
> When a file is renamed, it it automatically opened.

Sublime Text does that as soon as you right click. All FileManager does after that is retarget the view.

> Maybe we are able to automatically detect that...

I quickly looked, and I don't think that this is going to be possible. When you right click on a file in the side bar, it is automatically opened in this weird kind of state, which if I knew how to detect, I could then store and automatically close the view after the rename. But I don't :slightly_frowning_face: 

And always closing the file after rename isn't a good option because when you rename from the control panel, you expect the file to stay open (adding a setting to always close after rename would also be bad).

So, since I don't see a way to get this to work, I'm going to close this for now. If anyone knows how to detect the file's weird state, please reopen, it should then be trivial to implement.
