### ISSUE TITLE
Terminal under OS X doesn't work

### ISSUE THREAD

**Issue by kapooostin** [math2001/FileManager#3]
It seems that at the moment FileManager preferences have the instructions only for Windows. How do I set up it for OS X?

**Comment by math2001** [comment]
Oh, sorry, I haven't thought about OSX.

Do you know how to start a terminal **from** the terminal?

**Comment by kapooostin** [comment]
No. I tried to google it but without luck. Maybe this could help https://github.com/wbond/sublime_terminal.

**Comment by math2001** [comment]
Yep, I try google too, but without any success. `sublime_terminal` is an alternative. You can install it, I want to add a setting for each command in the side bar context menu to define if they're shown are not. 

I tried to look at the code of sublime_terminal but because I cannot try on OS X, it's really hard to understand.

So, I hope this is only a temporary solution (using Terminal), but I'll keep you in touch.

**Comment by math2001** [comment]
Hello! It's been a while, but I found this (in here)

```bash
open -a Terminal
```

I guess the `-a` options means `application`, which would make sense. Could you please try?

**Comment by ameistad** [comment]
Doesn't work. I get this error in the Sublime console:
`FileNotFoundError: [Errno 2] No such file or directory: 'open -a Terminal'`

**Comment by math2001** [comment]
Remember that you have access to `$cwd` in the `cmd`.
