### ISSUE TITLE
How to debug FileManager?

### ISSUE THREAD

**Issue by linkhanfeng** [math2001/FileManager#30]
I try debug `open_in_browser.py` use print(),
but console not input

**Comment by math2001** [comment]
Yeah it's because there is a bunch of imports, and ST doesn't reload nested scripts. So, you need to restart ST everytime you make a change to reload the whole plugin.

Otherwise, I wrote this little thing, and FileManager is automatically configured to work with it I think, you can give it a try. Here it is: https://github.com/math2001/sublime-plugin-reloader
