### ISSUE TITLE
conflict with azerty keyboard

### ISSUE THREAD

**Issue by kud** [math2001/FileManager#32]
Hello,

Just to tell you alt+n is a bit risky as command, because it's the way to have "~" on an azerty keyboard.

**Comment by redgluten** [comment]
And there doesn’t seem to be a clean way to restore its usage with the way Sublime works now. Adding another keybinding for `fm_create` while working does not overwrite the `alt+n` binding. Using something like `"keys": ["alt+n"], "command": "" }` is also not an option since the binding will still be intercepted. This is partly an issue with Sublime itself too but maybe it would be better not to put any keybindings by default? Or do you know any good solution to this issue?

**Comment by math2001** [comment]
I'm planning on changing this shortcut, maybe even removing it altogether (but explaining how to the user how to bind something themselves to `fm_create`).

To fix your issue now, you can add this to your keybindings:

```json
{
	"keys": ["alt+n"],
	"command": "insert",
	"args": {
		"characters": "~"
	}
}
```

What shortcut are you going to be using instead? I'm asking because I don't really have any other idea as a good default for this command... 🙂

**Comment by redgluten** [comment]
Thanks for your answer, I used this fix before but couldn’t find it anymore. It’s not ideal though but maybe the issue should be solved on Sublime side? Overriding global shortcuts without any easy way to tell what‘s going on or reverting behavior is not ideal…

Otherwise I think it is better to even remove the the binding altogether considering the situation and adding a message in the next update to explain why. I’m using `super+alt+n` for the `fm_create_` personally but it might not be ideal either. I’d say just let users set their own bindings, otherwise every plugin is polluting the bindings and it’s a pain to search what’s breaking what.

**Comment by math2001** [comment]
> otherwise every plugin is polluting the bindings and it’s a pain to search what’s breaking what.

Yep, I think that's what I will end up doing.

Here's another idea: add a setting to enable default keybindings (this would be a boolean setting in `FileManager.sublime-settings` using [`package_setting_context`](https://github.com/math2001/package_setting_context))

Basically, I would like things to work "out of the box", whilst not being a pain if it doesn't quite work for someone.

**Comment by math2001** [comment]
Oh wait, I've just realized this that I had already implemented that feature 3 years ago: https://github.com/math2001/FileManager/commit/c9dd7b1efabec450ed8f4249b22f152d2027ad37

The setting is called "create_keybinding_enabled". `Preferences: FileManager Settings`, and set add `"create_keybinding_enabled": false`.

The FileManager is somewhat extensive, but not discoverable and it doesn't include everything either. There should be a single document (probably the readme) listing common tips and tricks #52.
