### ISSUE TITLE
Update for delete confirm dialog

### ISSUE THREAD

**Issue by sharifzadesina** [math2001/FileManager#39]
Hi,

So there are two reasons for this update:
1- When you select many files for delete, it is hard to click on the `cancel` option by mouse.
2- It is better to use a `dialog` instead of `panel` so it will follow Sublime principles.

ToDo:
1- If there were more than for example `3` files selected, we will only show the number of selected files, and no file path will be shown.
2- We will use `ok_cancel_dialog` instead of `show_quick_panel` [here](https://github.com/math2001/FileManager/blob/master/FMcommands/delete.py#L28).

P.S. I can send a PR for this.

![Screencast from 2019-07-27 03 09 05](https://user-images.githubusercontent.com/15300551/61984990-38cc5980-b01c-11e9-942b-f3eaf10d7ecb.gif)

**Comment by math2001** [comment]
Hey Sina, I agree with your first point, but not with the second. I feel that the native cancel dialog feels kind of ugly, so that's why I choose to use this panel.

Go ahead an send a PR :-)

**Comment by TheSecEng** [comment]
I agree with the it being difficult to cancel but I also disagree with using a dialog.

Here are my thoughts:
1. Keep the file paths, I think it is valuable as if you have multi files named the same, you could see quickly if you selected the wrong one
2. Perhaps adding a option that if you type cancel into the dialog and hit `↩` then it would also cancel the delete
3. Can we add a file per line in the panel so that you can use the ↑ and ↓ to select individual files and hit ⌫ and have it be removed from the list and deleted on the sidebar

**Comment by TheSecEng** [comment]
Preview? Thoughts?

<img width="625" alt="Delete?" src="https://user-images.githubusercontent.com/32599364/72628556-8915db80-391c-11ea-8e0b-9a5ab2dce79b.png">

**Comment by TheSecEng** [comment]
See PR #60

**Comment by math2001** [comment]
:ok_hand: very neat
