### ISSUE TITLE
Copy relative path function outputs a string starting with "/"

### ISSUE THREAD

**Issue by bobmaerten** [math2001/FileManager#55]
Hi, I'm a very happy user of Filemanager plugin.

I have a relatively frequent use of the "copy relative path" function, but I could not find in the code/doc the reason why the string starts with a "/", making the relative intention to an absolute path.

Is it intentional? Then why? And could it be setup through a parameter?

Thanks a lot anyway for you work.

**Comment by math2001** [comment]
> Hi, I'm a very happy user of Filemanager plugin.

I'm very glad to here that, thanks for letting me know :hearts: 

> Is it intentional? Then why?

It was intentional, because it was meant as "relative from root". My use case is that when building a static website, `/` refers to the root folder in my program.

> And could it be setup through a parameter?

That's definitely possible, although [I've lately realized that this should be done with care](https://github.com/math2001/FileManager/issues/53#issue-545412263) (the bold part).

Right now, I'm thinking of adding another menu entry and renaming the current one (it's in a sub menu, so it won't cluster the user's context menu). `Relative path -> Path from root`, which would copy with the leading slash, and add `Relative path`, which would do what you expected in the first place (now that you point it out to me, it is indeed what makes the most sense).

What do you think? Would you be able to describe your use case? It would really help to make a better decision :slightly_smiling_face:

**Comment by bobmaerten** [comment]
Sorry I didn't take time to throroughtly the other issues and merely try to find a similar issue before creating this one. 

My use case is essentially when debugging, I want to quickly run tests for the current file, copy/pasting relative file path on `make test <paste relative file>` in my console. Or for doing some `git mv <paste> new_path` operations.

I read your position on intuitive behavior for a plugin, and I agree. In linters domain, there is also a growing tendency to have straightforward tools (like prettier) with little to no possible configuration, by letting users determine their core usages.

So in this direction, another menu available in the palette would settle the case.

PS: naming things is hard. Clear intent with a short label is hard too.

**Comment by math2001** [comment]
:tada: Thank you @bobmaerten for you feedback! I've just pushed the fix, don't hesitate to tell me what you think of it :slightly_smiling_face:

**Comment by bobmaerten** [comment]
Great! nothing changed in my workflow a a few keystrokes saved every time.
Notice that I cannot get the new command you added "Path from root" in the command palette.

Thanks anyway.

**Comment by math2001** [comment]
Damn. Sorry about that.
