### ISSUE TITLE
How to accept an intermediate path completion?

### ISSUE THREAD

**Issue by jpcirrus** [math2001/FileManager#56]
Firstly, many thanks for this project. Hits the sweet spot. Nice work!

Say I want to create a new file in a subfolder of a subfolder (say `figs`) of the first folder in the project (index `0`). Hitting tab cycles through candidate folders. When I get to `figs` how do I stop cycling and accept it ready to tab through the canditates of the next level of folders? The only way I have found is to enter a random letter, then delete that and invoke tab again.

**Comment by math2001** [comment]
> Firstly, many thanks for this project. Hits the sweet spot. Nice work!

Thank you :hearts: :slightly_smiling_face: 

> The only way I have found is to enter a random letter, then delete that and invoke tab again.

Yep, that's what I do too. I see that it's not the best, but i'm not sure how else could it be done...

How could FileManager "guess" that you are now happy with your current selection, and want to the "next set of completion" (from the subfolder). Do you have any ideas?

One idea: don't autocomplete the `/`. That means that you have to type it yourself, and hence indicates that you are happy with the current selection. But I kind of like having the `/` inserted automatically.

Here's the thing though: if you are hitting tab *straight away* to get completion, that probably means you want to "browse" what's in that folder. And so that means you probably want to use the browser :wink: Just hit enter, it'll show up a command palette with all the folder and files listed. You can browse this way for as long as you want, and then if you want create the file from there, select "create from here".

Can you tell me what you think about this option?

<details>
<summary>
Just trying to predict what you are going to say/feel. Don't read it yet :slightly_smiling_face: 
</summary>
I'm guessing the main downside is that it breaks your flow...
</details>

**Comment by jpcirrus** [comment]
> One idea: don't autocomplete the /.

I think that is a good idea because you have to type *something* to indicate the desired completion, and one keystroke is better than the current two. But, I hadn't thought about using the browser functionality and now that I have been trying that find it much faster to complete in paths I am not familiar with and so can't provide a good guess as to the start of the next path fragment. I think that I will mostly use that functionality as it will be faster than tab completion on unfamiliar paths.

The only thing I can think of improving with the browser is that when there are no more paths to navigate that the option `[cmd] Create from here` is marked for selection, to save one keystroke. 

Thanks.

**Comment by math2001** [comment]
> when there are no more paths to navigate

Do you mean no more folders, or no more files or folder?

**Comment by jpcirrus** [comment]
>> when there are no more paths to navigate

> Do you mean no more folders, or no more files or folder?

No more files or folders

**Comment by math2001** [comment]
Done. Thank you for you help @jpcirrus :slightly_smiling_face: Don't hesitate to let me know what you think of this feature.

**Comment by jpcirrus** [comment]
Thanks @math2001, that's it 🥇
