### ISSUE TITLE
Allow user to remap key commands

### ISSUE THREAD

**Issue by soifou** [math2001/FileManager#9]
Since your commit [3e76d1c](https://github.com/math2001/FileManager/commit/3e76d1cfa823b9a451b06a1b50498d0e9148ddf7), you remap the `fm_create` command to `alt+n` shortcut. 

However on macOS this shortcut is triggered to write tilde char `~`, which is heavily used on dev purpose. As workaround, I edited my macOS keymap `Default (OSX).sublime-keymap` to "revert" your change like this:

```
{ "keys": ["alt+n"], "command": "insert", "args": {"characters": "~"} },
{ "keys": ["ctrl+n"], "command": "fm_create" },
```

It would be nice if you could give us the possibility to choose our own keymap depending on the OSes for this command as does the package [PlainTasks](https://github.com/aziz/PlainTasks) for example. 

Thanks anyway for this useful package!

**Comment by math2001** [comment]
Yes, indeed, that's not a good keybinding on Mac OS.

I think a good solution would be to do what you just did (platform specific keymaps) *and* add a setting `use_default_keymap_create`, which would enable/disable this default keymap (since it's the only one for now), Like this, there would be no need to tweak the package to just change the keybindings. 

Now that I re-read the thread about changing the shortcut:

> Alt+n will type ˜ in Mac OS, I do not know others' opinion

I don't know how I missed this...

Alright, so, I'm quiet busy right now, but this should be fixed soon.

> Thanks anyway for this useful package!

Happy you like it!
